2019-11-13 16:56:57,962 : kivy : Factory: 184 symbols loaded
2019-11-13 16:56:58,053 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-11-13 16:56:58,105 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2019-11-13 16:56:58,105 : kivy : Video: Provider: gstplayer
2019-11-13 16:56:58,164 : kivy : Loading MPF-MC controller
2019-11-13 16:56:58,164 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2019-11-13 16:56:58,168 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.67
2019-11-13 16:56:58,168 : mpfmc : Machine path: D:\mpf\wows\wows
2019-11-13 16:56:58,170 : ConfigProcessor : Config file in cache changed: D:\mpf\wows\wows\config\config
2019-11-13 16:56:58,170 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2019-11-13 16:56:58,214 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-11-13 16:56:58,221 : ConfigProcessor : Loading config from file D:\mpf\wows\wows\config\config.
2019-11-13 16:56:58,229 : kivy : YAML error found in file D:\mpf\wows\wows\config\config.yaml. Line 47, Position 7: while parsing a block collection
  in "D:\mpf\wows\wows\config\config.yaml", line 46, column 7
expected <block end>, but found '?'
  in "D:\mpf\wows\wows\config\config.yaml", line 47, column 7
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 162, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 500, in parse_block_sequence_entry
    token.id, token.start_mark)
ruamel.yaml.parser.ParserError: while parsing a block collection
  in "D:\mpf\wows\wows\config\config.yaml", line 46, column 7
expected <block end>, but found '?'
  in "D:\mpf\wows\wows\config\config.yaml", line 47, column 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file D:\mpf\wows\wows\config\config.yaml. Line 47, Position 7: while parsing a block collection
  in "D:\mpf\wows\wows\config\config.yaml", line 46, column 7
expected <block end>, but found '?'
  in "D:\mpf\wows\wows\config\config.yaml", line 47, column 7
2019-11-13 16:56:58,233 : kivy : Stopping child threads... (0 remaining)
2019-11-13 16:56:58,237 : kivy : All child threads stopped.
