2019-11-16 15:16:21,324 : kivy : Factory: 184 symbols loaded
2019-11-16 15:16:21,415 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-11-16 15:16:21,468 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2019-11-16 15:16:21,469 : kivy : Video: Provider: gstplayer
2019-11-16 15:16:21,524 : kivy : Loading MPF-MC controller
2019-11-16 15:16:21,524 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2019-11-16 15:16:21,525 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.68
2019-11-16 15:16:21,525 : mpfmc : Machine path: D:\mpf\wows\wows
2019-11-16 15:16:21,526 : ConfigProcessor : Config file in cache changed: D:\mpf\wows\wows\config\config
2019-11-16 15:16:21,527 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2019-11-16 15:16:21,570 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-11-16 15:16:21,578 : ConfigProcessor : Loading config from file D:\mpf\wows\wows\config\config.
2019-11-16 15:16:21,630 : ConfigProcessor : Loading config: D:\mpf\wows\wows\config\config
2019-11-16 15:16:21,631 : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\31418c17c7947b0b26bf3ae2a4803514.mpf_cache
2019-11-16 15:16:21,632 : mpfmc : Starting clock at 60.0Hz
2019-11-16 15:16:21,643 : kivy : Text: Provider: sdl2
2019-11-16 15:16:21,680 : kivy : Window: Provider: sdl2
2019-11-16 15:16:22,037 : kivy : GL: Using the "OpenGL" graphics system
2019-11-16 15:16:22,041 : kivy : GL: GLEW initialization succeeded
2019-11-16 15:16:22,041 : kivy : GL: Backend used <glew>
2019-11-16 15:16:22,041 : kivy : GL: OpenGL version <b'4.6.0 NVIDIA 388.13'>
2019-11-16 15:16:22,042 : kivy : GL: OpenGL vendor <b'NVIDIA Corporation'>
2019-11-16 15:16:22,042 : kivy : GL: OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
2019-11-16 15:16:22,042 : kivy : GL: OpenGL parsed version: 4, 6
2019-11-16 15:16:22,042 : kivy : GL: Shading version <b'4.60 NVIDIA'>
2019-11-16 15:16:22,043 : kivy : GL: Texture max size <32768>
2019-11-16 15:16:22,043 : kivy : GL: Texture max units <32>
2019-11-16 15:16:22,058 : kivy : Window: auto add sdl2 input provider
2019-11-16 15:16:22,059 : kivy : Window: virtual keyboard not allowed, single mode, not docked
2019-11-16 15:16:22,067 : SoundSystem : SoundSystem: Using default 'sound_system' settings
2019-11-16 15:16:22,248 : AudioInterface : Initialized
2019-11-16 15:16:22,248 : SoundSystem : No audio tracks are specified in your machine config file. a track named 'default' has been created.
2019-11-16 15:16:22,250 : kivy : Base: Start application main loop
2019-11-16 15:16:22,251 : EventManager : Event: ======'display_window_initialized'====== Args={}
2019-11-16 15:16:22,287 : mpfmc : Display: Setting 'window' as default display
2019-11-16 15:16:22,293 : EventManager : Event: ======'displays_initialized'====== Args={}
2019-11-16 15:16:22,294 : EventManager : Event: ======'slide_window_blank_created'====== Args={}
2019-11-16 15:16:22,294 : EventManager : Event: ======'display_window_ready'====== Args={}
2019-11-16 15:16:22,303 : EventManager : Event: ======'init_phase_1'====== Args={}
2019-11-16 15:16:22,306 : EventManager : Event: ======'mc_ready'====== Args={}
2019-11-16 15:16:22,306 : EventManager : Event: ======'init_phase_2'====== Args={}
2019-11-16 15:16:22,307 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2019-11-16 15:16:22,308 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2019-11-16 15:16:22,308 : kivy : Base: Leaving application in progress...
2019-11-16 15:16:22,308 : kivy : Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x0000018145FBAE10>>, priority=1, kwargs={}, key=UUID('4312e663-c9ea-4eee-835e-8eb7c184268b'), condition=None, blocking_facility=None) for event init_phase_2
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 662, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 59, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 90, in _load_mode
    .format(mode_string))
ValueError: No folder found for mode 'base'. Is your mode folder in your machine's 'modes' folder?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\clock.py", line 591, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\uix\display.py", line 205, in _displays_initialized
    self.mc.displays_initialized()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 336, in displays_initialized
    self._init()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 380, in _init
    self.events.process_event_queue()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 743, in process_event_queue
    **event[3])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 708, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 664, in _run_handlers
    raise Exception("Exception while processing {} for event {}".format(handler, event)) from e
Exception: Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x0000018145FBAE10>>, priority=1, kwargs={}, key=UUID('4312e663-c9ea-4eee-835e-8eb7c184268b'), condition=None, blocking_facility=None) for event init_phase_2
2019-11-16 15:16:22,311 : kivy : Stopping child threads... (1 remaining)
2019-11-16 15:16:23,315 : kivy : All child threads stopped.
