2020-03-14 15:36:06,570 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.2
2020-03-14 15:36:06,570 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-03-14-15-36-06-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-03-14 15:36:06,570 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2020-03-14 15:36:06,570 : INFO : Machine : Machine path: E:\mpf\wows\wows
2020-03-14 15:36:06,570 : INFO : Machine : Platform: win32
2020-03-14 15:36:06,570 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2020-03-14 15:36:06,571 : INFO : Machine : Python version: 3.6.4 (64-bit)
2020-03-14 15:36:06,571 : INFO : Machine : Machine config file #1: config.yaml
2020-03-14 15:36:06,571 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a7e9e9e882fa7eca7cb0ba00eaf15121.mpf_cache
2020-03-14 15:36:06,574 : INFO : Machine : Initialise MPF.
2020-03-14 15:36:06,807 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,845 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2020-03-14 15:36:06,845 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.2', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,845 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.2, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,845 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,845 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,845 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,846 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,846 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,846 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2020-03-14 15:36:06,846 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-03-14 15:36:06,878 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\79b69aca05077178b8904472f0120320.mpf_cache
2020-03-14 15:36:06,880 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\97f63c0afcbce8d9df7044fccf1035a4.mpf_cache
2020-03-14 15:36:06,882 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\edfeac6524e6d1874b234b23d854175f.mpf_cache
2020-03-14 15:36:06,884 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\4aeaa69609f53d9b71d1dbbedd434b0b.mpf_cache
2020-03-14 15:36:06,886 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\bafdfa3518b80fac5c67bbc1ea3da4f8.mpf_cache
2020-03-14 15:36:06,888 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a6527a592b6034dbfea56fdf726c3822.mpf_cache
2020-03-14 15:36:06,890 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d01089fe8a4c8b32515bd43f8cd9fd8b.mpf_cache
2020-03-14 15:36:06,892 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1e6cc6775e87a3e14ded8d45fd065b10.mpf_cache
2020-03-14 15:36:06,894 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\f9a57b3955e1480227d6e8589f6567c4.mpf_cache
2020-03-14 15:36:06,896 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\fbcc5772262340622f93ebd98450e45f.mpf_cache
2020-03-14 15:36:06,898 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\2242affd3e515f08e26d4d5b365e866b.mpf_cache
2020-03-14 15:36:06,900 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\6e6d4708a613edd7635d35a6961997f3.mpf_cache
2020-03-14 15:36:06,902 : WARNING : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\modes\detonation\config\detonation.yaml
2020-03-14 15:36:06,902 : INFO : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\detonation\config\detonation.yaml.
2020-03-14 15:36:06,911 : INFO : ConfigProcessor : Loading config: E:\mpf\wows\wows\modes\detonation\config\detonation.yaml
2020-03-14 15:36:06,911 : INFO : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\fff0d16f8200200b52cd28c2ea815f12.mpf_cache
2020-03-14 15:36:06,913 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2020-03-14 15:36:06,918 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2020-03-14 15:36:06,922 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\f6b4884431efff4cb2e21d23d2c7b801.mpf_cache
2020-03-14 15:36:06,924 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\2f7452aae1b2779bb4a1388fc419c0c8.mpf_cache
2020-03-14 15:36:06,926 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\fa61b88f86d6e414c9b51ac1d3e19568.mpf_cache
2020-03-14 15:36:06,928 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5dbeda7d2775496a54d206d506904281.mpf_cache
2020-03-14 15:36:06,930 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\fa1d48c05f4d8fd05f0b267836a1ac4f.mpf_cache
2020-03-14 15:36:06,962 : INFO : EventManager : Event: ======'main_state'====== Args={}
2020-03-14 15:36:06,962 : INFO : EventManager : Event: ======'lock_lit_started'====== Args={}
2020-03-14 15:36:06,962 : WARNING : Mode.confederate : Can only start mode confederate during a game. Aborting start.
2020-03-14 15:36:06,962 : WARNING : Mode.hc_lock_lit : Can only start mode hc_lock_lit during a game. Aborting start.
2020-03-14 15:36:06,963 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2020-03-14 15:36:06,963 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>)
2020-03-14 15:36:06,963 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>)
2020-03-14 15:36:06,964 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>)
2020-03-14 15:36:06,964 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>)
2020-03-14 15:36:06,964 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>)
2020-03-14 15:36:06,964 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>)
2020-03-14 15:36:06,971 : ERROR : asyncio : Exception in callback EventManager._done(<Task finishe...ights None',)>)
handle: <Handle EventManager._done(<Task finishe...ights None',)>)>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 698, in _done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 615, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 96, in initialise_modes
    mode.initialise_mode()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 577, in initialise_mode
    **item.kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 53, in _process_config_shows_section
    self.register_show(show, settings)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 66, in register_show
    file=None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 76, in __init__
    self._do_load_show(data=data)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 174, in _do_load_show
    self._process_step_actions(step, actions)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 204, in _process_step_actions
    actions[key] = self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\device_config_player.py", line 43, in validate_config_entry
    name, self.show_section, settings))
AssertionError: Invalid settings for player blue:lights None
2020-03-14 15:36:06,987 : INFO : Machine : Starting the main run loop.
2020-03-14 15:36:06,989 : INFO : Machine : Shutting down...
2020-03-14 15:36:06,990 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-03-14 15:36:06,991 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 698, in _done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 615, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 96, in initialise_modes
    mode.initialise_mode()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 577, in initialise_mode
    **item.kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 53, in _process_config_shows_section
    self.register_show(show, settings)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 66, in register_show
    file=None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 76, in __init__
    self._do_load_show(data=data)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 174, in _do_load_show
    self._process_step_actions(step, actions)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 204, in _process_step_actions
    actions[key] = self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\device_config_player.py", line 43, in validate_config_entry
    name, self.show_section, settings))
AssertionError: Invalid settings for player blue:lights None
2020-03-14 15:36:06,993 : INFO : root : MPF run loop ended.
