2020-01-25 12:04:19,002 : kivy : Factory: 184 symbols loaded
2020-01-25 12:04:19,096 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2020-01-25 12:04:19,146 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2020-01-25 12:04:19,147 : kivy : Video: Provider: gstplayer
2020-01-25 12:04:19,211 : kivy : Loading MPF-MC controller
2020-01-25 12:04:19,211 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2020-01-25 12:04:19,212 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.68
2020-01-25 12:04:19,212 : mpfmc : Machine path: E:\mpf\wows\wows
2020-01-25 12:04:19,213 : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\config\config
2020-01-25 12:04:19,213 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2020-01-25 12:04:19,257 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2020-01-25 12:04:19,264 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\config\config.
2020-01-25 12:04:19,323 : kivy : YAML error found in file E:\mpf\wows\wows\config\config.yaml. Line 365, Position 1: while scanning a simple key
  in "E:\mpf\wows\wows\config\config.yaml", line 363, column 3
could not find expected ':'
  in "E:\mpf\wows\wows\config\config.yaml", line 365, column 1
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 162, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 486, in parse_block_sequence_entry
    if self.scanner.check_token(BlockEntryToken):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 159, in check_token
    while self.need_more_tokens():
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 196, in need_more_tokens
    self.stale_possible_simple_keys()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 345, in stale_possible_simple_keys
    "could not find expected ':'", self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "E:\mpf\wows\wows\config\config.yaml", line 363, column 3
could not find expected ':'
  in "E:\mpf\wows\wows\config\config.yaml", line 365, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file E:\mpf\wows\wows\config\config.yaml. Line 365, Position 1: while scanning a simple key
  in "E:\mpf\wows\wows\config\config.yaml", line 363, column 3
could not find expected ':'
  in "E:\mpf\wows\wows\config\config.yaml", line 365, column 1
2020-01-25 12:04:19,361 : kivy : Stopping child threads... (0 remaining)
2020-01-25 12:04:19,362 : kivy : All child threads stopped.
